settings: fix regexp syntax, add a test
Trying to compile this regexp fails with:

    re.error: unbalanced parenthesis at position 5

I introduced this bug in 45a1146e1122b376ddac312687e8e27d4e0a8076. Fix
it, and add a small test case that would have caught it.